### ISSUE TITLE
Django和Python环境版本

### ISSUE THREAD

**Issue by Run0099** [Pzqqt/Django_Transportation_Management_System#1]
请问一下作者项目中使用的Python和Django是什么版本的，可以告诉一下嘛，可以有偿！

**Comment by Pzqqt** [comment]
> 请问一下作者项目中使用的Python和Django是什么版本的，可以告诉一下嘛，可以有偿！

这个没有要求，使用最新版本就行。我使用的是Python 3.9.10，Django 4.0.3。

项目本身就是个练手项目，半成品，参考学习下玩玩就好。

**Comment by Run0099** [comment]
您好，首先感谢您的热情回复。情况是这样的：我最近在学习相关知识，想加您微信请教交流，你看方便吗？我的微信号：1091108001



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 晚上8:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Pzqqt/Django_Transportation_Management_System] Django和Python环境版本 (Issue #1)





  
请问一下作者项目中使用的Python和Django是什么版本的，可以告诉一下嘛，可以有偿！
  
这个没有要求，使用最新版本就行。我使用的是Python 3.9.10，Django 4.0.3。
 
项目本身就是个练手项目，半成品，参考学习下玩玩就好。

**Comment by Pzqqt** [comment]
> 您好，首先感谢您的热情回复。情况是这样的：我最近在学习相关知识，想加您微信请教交流，你看方便吗？我的微信号：*********

这个不行，我最近要准备考试，没有太多时间，并且我也不经常用微信。有问题的话可以在这里说，或者发邮件。
