### ISSUE TITLE
项目Run不起来

### ISSUE THREAD

**Issue by NanmiCoder** [Pzqqt/Django_Transportation_Management_System#2]
大神您好：
  git clone 本项目之后，执行./init_database.sh会报错,错误如下：
![image](https://user-images.githubusercontent.com/47178017/163720194-a137bb86-0a8b-4fcc-a25c-76d809cad39e.png)
  ps: mac和linux下系统都尝试了，还是会报错

尝试不用shell来初始化项目，执行迁移命令makemigrations时，会报错表不存在：
![image](https://user-images.githubusercontent.com/47178017/163720256-b29aa1d1-a9eb-4257-b514-19f866dcc15b.png)
项目migrations目录的除开init.py都删除了的
不知道您.gitignore中是否漏了本项目的必要文件，导致项目初始化不成功
希望您看到issues回复下，谢谢啦
本人邮箱: relakkes@gmail.com

**Comment by Pzqqt** [comment]
> 大神您好： git clone 本项目之后，执行./init_database.sh会报错,错误如下： ![image](https://user-images.githubusercontent.com/47178017/163720194-a137bb86-0a8b-4fcc-a25c-76d809cad39e.png) ps: mac和linux下系统都尝试了，还是会报错
> 
> 尝试不用shell来初始化项目，执行迁移命令makemigrations时，会报错表不存在： ![image](https://user-images.githubusercontent.com/47178017/163720256-b29aa1d1-a9eb-4257-b514-19f866dcc15b.png) 项目migrations目录的除开init.py都删除了的 不知道您.gitignore中是否漏了本项目的必要文件，导致项目初始化不成功 希望您看到issues回复下，谢谢啦 本人邮箱: [relakkes@gmail.com](mailto:relakkes@gmail.com)

问题已修复，请同步到最新的源码并再试一次。~~没想到`git apply`对差异补丁中的行号要求也这么严格。。。~~

**Comment by NanmiCoder** [comment]
感谢，可以Run起来了，另外建议在Readme中把adminlte-3.0.5的安装方法也写清楚一下，可能有部分同学找不到这个前端模板在哪里安装，还有就是后台的访问地址也可以写一下，不然还得通过url是去看真正的后台地址。

**Comment by Pzqqt** [comment]
> 感谢，可以Run起来了，另外建议在Readme中把adminlte-3.0.5的安装方法也写清楚一下，可能有部分同学找不到这个前端模板在哪里安装，还有就是后台的访问地址也可以写一下，不然还得通过url是去看真正的后台地址。

AdminLTE-3.0.5是作为项目中的子模块（submodule）而存在的，运行`git submodule init`和`git submodule update`之后就可以了，不需要手动安装。而且项目中使用的AdminLTE-3.0.5是我自己fork的分支，只保留了dist和plugins，并且更新了一些过时的插件。

**Comment by NanmiCoder** [comment]
收到～ 非常感谢～
