### ISSUE TITLE
404报错

### ISSUE THREAD

**Issue by 0xAyin** [Pzqqt/Django_Transportation_Management_System#4]
环境搭建后，会报404错

**Comment by 0xAyin** [comment]
windows搭建欢迎以后，访问8000端口，无法访问tms和utils的url

**Comment by 0xAyin** [comment]
求解

**Comment by Pzqqt** [comment]
你为什么不看README.md中的Usage呢？

**Comment by 0xAyin** [comment]
您好，查看readme.md中的usage后，遇到了一个问题是主页访问404，其中admin访问成功，而tms和utils的页面是404的状态，另外一个问题是登录的时候在数据库新建新的账户，在主界面无法登录顺利，方便的话还请留个社交方式联系一下，感谢，QQ:593428010,有偿

**Comment by Pzqqt** [comment]
> 您好，查看readme.md中的usage后，遇到了一个问题是主页访问404，其中admin访问成功，而tms和utils的页面是404的状态，另外一个问题是登录的时候在数据库新建新的账户，在主界面无法登录顺利，方便的话还请留个社交方式联系一下，感谢，QQ:593428010,有偿

QQ已加，详细在QQ上说。

另外，从Admin管理后台添加用户是不可行的，因为密码那一项在保存至数据库时需要调用`django.contrib.auth.hashers.make_password`方法进行哈希变换（绝对不能在数据库中明文保存密码）。你直接在Admin管理后台添加用户时，输入的密码被明文保存到了数据库，这样的话在login视图函数中无法正常处理，`django.contrib.auth.hashers.check_password`方法调用返回False，就导致无法登录了。

我刚才更新了存储库，增加了添加用户的功能，在TMS登录管理员用户之后就可以添加用户了。
