### ISSUE TITLE
为什么启动起来是这样的，这个前端不知道怎么回事

### ISSUE THREAD

**Issue by lizhiyou88** [Pzqqt/Django_Transportation_Management_System#8]
![image](https://user-images.githubusercontent.com/39184961/205473682-c922ac20-55d2-4676-a749-08950a1c390e.png)
![image](https://user-images.githubusercontent.com/39184961/205473704-24e86c97-8c71-4abf-b82c-97f3546894bb.png)

**Comment by Pzqqt** [comment]
说明“同步AdminLTE-3.0.5”这一步没有做好。
